/**
 * Query-parameter parsing for the `/embed` surface.
 *
 * Embed URLs are written by hand (or generated by the loader script) on
 * third-party websites, so every value is untrusted: unknown enum members,
 * absurd page sizes and junk numbers must degrade to a sane default rather
 * than 500 the iframe. Everything here is a pure function so it can be unit
 * tested without a request.
 */

import type { EventType } from '$lib/api/generated/types.gen';
import { sanitizeUtmValue } from '$lib/utils/attribution';
import {
	EMBED_DEFAULT_PAGE_SIZE,
	EMBED_MAX_PAGE_SIZE,
	EMBED_THEMES,
	type EmbedTheme
} from './constants';

/** Discovery filters an embed may forward to the public event list. */
export interface EmbedListFilters {
	tags: string[] | null;
	cityId: number | null;
	eventType: EventType | null;
	eventSeries: string | null;
	includePast: boolean;
	orderBy: 'start' | '-start';
	pageSize: number;
}

const EVENT_TYPES: readonly EventType[] = ['public', 'private', 'members-only'];

/** `?theme=` → a known theme, defaulting to `auto`. */
export function parseEmbedTheme(raw: string | null | undefined): EmbedTheme {
	return (EMBED_THEMES as readonly string[]).includes(raw ?? '') ? (raw as EmbedTheme) : 'auto';
}

/**
 * `?utm_content=` is appended by the loader script and carries the *host page*
 * hostname. Same charset as every campaign tag — single authority lives in
 * `$lib/utils/attribution.ts` (mirrors the backend sanitiser).
 */
export function sanitizeUtmContent(raw: string | null | undefined): string | null {
	return sanitizeUtmValue(raw);
}

/** Host-page campaign tags forwarded by the loader; replace the embed convention entirely. */
export interface UtmOverride {
	utm_source: string;
	utm_medium?: string;
	utm_campaign?: string;
	utm_content?: string;
}

/**
 * The organizer's own campaign tags win (#880, decided 2026-09-08): when the host
 * page carried a valid `utm_source`, the embed's outbound links use the host's
 * tags verbatim and none of the `embed / <surface> / <org slug> / <hostname>`
 * defaults. No valid `utm_source` → no override.
 */
export function parseUtmOverride(params: URLSearchParams): UtmOverride | null {
	const source = sanitizeUtmValue(params.get('utm_source'));
	if (!source) return null;
	const override: UtmOverride = { utm_source: source };
	const medium = sanitizeUtmValue(params.get('utm_medium'));
	const campaign = sanitizeUtmValue(params.get('utm_campaign'));
	const content = sanitizeUtmValue(params.get('utm_content'));
	if (medium) override.utm_medium = medium;
	if (campaign) override.utm_campaign = campaign;
	if (content) override.utm_content = content;
	return override;
}

/**
 * Parse a boolean-ish query value. Anything other than an explicit truthy
 * token is false — an embed should never silently start showing past events.
 */
function parseBool(raw: string | null): boolean {
	return raw === 'true' || raw === '1' || raw === 'yes';
}

function parseIntOrNull(raw: string | null): number | null {
	if (raw === null || raw.trim() === '') return null;
	const parsed = Number(raw);
	return Number.isInteger(parsed) ? parsed : null;
}

/**
 * `?tags=` accepts either repeated params (`tags=a&tags=b`) or a single
 * comma-separated value (`tags=a,b`) — the loader script emits the latter
 * from a `data-revel-tags` attribute.
 */
export function parseEmbedTags(params: URLSearchParams): string[] | null {
	const tags = params
		.getAll('tags')
		.flatMap((value) => value.split(','))
		.map((value) => value.trim())
		.filter((value) => value.length > 0);
	return tags.length > 0 ? tags : null;
}

/** Parse the discovery filters a list/series embed forwards to the API. */
export function parseEmbedListFilters(params: URLSearchParams): EmbedListFilters {
	const rawPageSize = parseIntOrNull(params.get('page_size'));
	const pageSize =
		rawPageSize === null || rawPageSize < 1
			? EMBED_DEFAULT_PAGE_SIZE
			: Math.min(rawPageSize, EMBED_MAX_PAGE_SIZE);

	const rawEventType = params.get('event_type');
	const rawCityId = parseIntOrNull(params.get('city_id'));

	return {
		tags: parseEmbedTags(params),
		cityId: rawCityId !== null && rawCityId > 0 ? rawCityId : null,
		eventType: (EVENT_TYPES as readonly string[]).includes(rawEventType ?? '')
			? (rawEventType as EventType)
			: null,
		eventSeries: params.get('event_series') || null,
		includePast: parseBool(params.get('include_past')),
		orderBy: params.get('order_by') === '-start' ? '-start' : 'start',
		pageSize
	};
}
