// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
/// <reference types="@sveltejs/kit" />
import type { RevelUserSchema } from '$lib/api';
import '@testing-library/jest-dom/vitest';

declare global {
	namespace App {
		// interface Error {}
		interface Locals {
			// User can be full RevelUserSchema (from API) or minimal JWT data (from
			// token decode). The decoded access token is guaranteed to carry an id
			// (user_id/sub) but `email` is an optional claim — it is not present in
			// the backend's access token, so the minimal variant must not require it.
			user?:
				| (RevelUserSchema & { accessToken?: string })
				| { id: string; email?: string; accessToken?: string }
				| null;
			// Per-request correlation id (UUID). Generated by handleRequestLogging,
			// forwarded upstream as X-Request-ID so frontend and backend log lines
			// for the same request line up in Loki.
			requestId?: string;
		}
		// interface PageData {}
		// interface PageState {}
		// interface Platform {}
	}
}

export {};
