name: Test

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - src/**/*.ts
      - src/**/*.svelte
      - src/**/*.js
      - package.json
      - pnpm-lock.yaml
      - svelte.config.js
      - vite.config.ts
      - tsconfig.json

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check pnpm-lock.yaml is in sync
        run: |
          if ! git diff --exit-code pnpm-lock.yaml > /dev/null; then
            echo "❌ pnpm-lock.yaml is out of sync with package.json. Run 'pnpm install' and commit the updated lockfile."
            git diff pnpm-lock.yaml
            exit 1
          fi

      - name: Run type checking
        run: pnpm check

      - name: Run linting
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Run build
        run: pnpm build
        env:
          PUBLIC_API_URL: http://localhost:8000
